import {
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiNextdotjs,
  SiReact,
  SiReactquery,
  SiTailwindcss,
  SiRadixui,
  SiAntdesign,
  SiStyledcomponents,
  SiGithub,
  SiFigma,
  SiVercel,
  SiSentry,
  SiRedux,
  SiZod,
  SiVitest,
} from "react-icons/si";
import { type TechItem } from "@/shared/ui/tech-detail-modal";
import { ZustandIcon, EmotionIcon, PlaywrightIcon } from "./skills-icons";

export const SKILLS: TechItem[] = [
  {
    category: "Language",
    name: "TypeScript",
    description: "",
    url: "https://www.typescriptlang.org",
    Icon: SiTypescript,
  },
  {
    category: "Language",
    name: "JavaScript",
    description: "",
    url: "https://developer.mozilla.org/ko/docs/Web/JavaScript",
    Icon: SiJavascript,
  },
  {
    category: "Language",
    name: "HTML",
    description: "",
    url: "https://developer.mozilla.org/ko/docs/Web/HTML",
    Icon: SiHtml5,
  },
  {
    category: "Language",
    name: "CSS",
    description: "",
    url: "https://developer.mozilla.org/ko/docs/Web/CSS",
    Icon: SiCss3,
  },
  {
    category: "Framework",
    name: "Next.js",
    description: "",
    url: "https://nextjs.org",
    Icon: SiNextdotjs,
  },
  {
    category: "Library",
    name: "React",
    description: "",
    url: "https://react.dev",
    Icon: SiReact,
  },
  {
    category: "Library",
    name: "TanStack Query",
    description: "",
    url: "https://tanstack.com/query",
    Icon: SiReactquery,
  },
  {
    category: "Library",
    name: "Zustand",
    description: "",
    url: "https://zustand-demo.pmnd.rs",
    Icon: ZustandIcon,
  },
  {
    category: "Library",
    name: "Redux",
    description: "",
    url: "https://redux.js.org",
    Icon: SiRedux,
  },
  {
    category: "Library",
    name: "Zod",
    description: "",
    url: "https://zod.dev",
    Icon: SiZod,
  },
  {
    category: "Styling",
    name: "Tailwind CSS",
    description: "",
    url: "https://tailwindcss.com",
    Icon: SiTailwindcss,
  },
  {
    category: "Styling",
    name: "Radix UI",
    description: "",
    url: "https://www.radix-ui.com",
    Icon: SiRadixui,
  },
  {
    category: "Styling",
    name: "Ant Design",
    description: "",
    url: "https://ant.design",
    Icon: SiAntdesign,
  },
  {
    category: "Styling",
    name: "Styled Components",
    description: "",
    url: "https://styled-components.com",
    Icon: SiStyledcomponents,
  },
  {
    category: "Styling",
    name: "Emotion",
    description: "",
    url: "https://emotion.sh",
    Icon: EmotionIcon,
  },
  {
    category: "Tools",
    name: "GitHub",
    description: "",
    url: "https://github.com",
    Icon: SiGithub,
  },
  {
    category: "Tools",
    name: "Figma",
    description: "",
    url: "https://www.figma.com",
    Icon: SiFigma,
  },
  {
    category: "Tools",
    name: "Vercel",
    description: "",
    url: "https://vercel.com",
    Icon: SiVercel,
  },
  {
    category: "Tools",
    name: "Sentry",
    description: "",
    url: "https://sentry.io",
    Icon: SiSentry,
  },
  {
    category: "Testing",
    name: "Vitest",
    description: "",
    url: "https://vitest.dev",
    Icon: SiVitest,
  },
  {
    category: "Testing",
    name: "Playwright",
    description: "",
    url: "https://playwright.dev",
    Icon: PlaywrightIcon,
  },
];

export const CATEGORIES = [
  "Language",
  "Framework",
  "Library",
  "Styling",
  "Tools",
  "Testing",
] as const;
